### ISSUE TITLE
Regular updates

### ISSUE THREAD

**Issue by keepgoing1995** [nextstrain/flu_frequencies#39]
I've noticed that the sequencing data was last updated almost 6 months ago.
Are there plans to update it regularly in the future? @huddlej

**Comment by huddlej** [comment]
Hi @keepgoing1995, thank you for asking about this! We just updated the website with data as of late July. We will most likely update the website 6 times per year (3 times per WHO vaccine composition meeting periods in September and February), but it is possible we will update more regularly as we find value in the web application view of these data.

**Comment by keepgoing1995** [comment]
> Hi @keepgoing1995, thank you for asking about this! We just updated the website with data as of late July. We will most likely update the website 6 times per year (3 times per WHO vaccine composition meeting periods in September and February), but it is possible we will update more regularly as we find value in the web application view of these data.

Hey, @huddlej! Are you planning to update the Nextstrain dataset with the new vaccine variants?
